INSERT INTO tipo_necesidad (nombre, descripcion) 
VALUES 
    ('Alimentación saludable', 'Promoción de una alimentación adecuada para estudiantes y docentes.'),
    ('Atención de estudiantes con BAP', 'Apoyo a estudiantes con barreras para el aprendizaje y la participación.'),
    ('Comunidades de aprendizaje', 'Estrategias para fomentar el trabajo colaborativo entre educadores y estudiantes.'),
    ('Comunicación efectiva con comunidad escolar', 'Desarrollo de habilidades de comunicación dentro del entorno educativo.'),
    ('Convivencia escolar / Cultura de paz / Valores', 'Fomento del respeto, la inclusión y la paz en el ambiente escolar.'),
    ('Disciplina positiva', 'Metodologías de enseñanza enfocadas en la educación sin castigos físicos ni psicológicos.'),
    ('Educación inclusiva', 'Estrategias para garantizar una educación equitativa para todos los estudiantes.'),
    ('Enseñanza de lectura y matemáticas', 'Metodologías para mejorar el aprendizaje de lectura y matemáticas.'),
    ('Evaluación', 'Herramientas y estrategias para evaluar el aprendizaje de los estudiantes.'),
    ('Herramientas digitales para la educación / Innovación tecnológica', 'Uso de tecnología para mejorar los procesos educativos.'),
    ('Inteligencia emocional', 'Desarrollo de habilidades socioemocionales en la comunidad educativa.'),
    ('Lectoescritura', 'Estrategias para mejorar el desarrollo de la lectura y la escritura.'),
    ('Liderazgo y habilidades directivas', 'Capacitación para líderes escolares y administrativos.'),
    ('Metodologías activas', 'Enfoques de enseñanza innovadores como el aprendizaje basado en proyectos y gamificación.'),
    ('Neuroeducación', 'Aplicación de conocimientos sobre el cerebro en los procesos de aprendizaje.'),
    ('Nueva Escuela Mexicana', 'Implementación del nuevo modelo educativo en México.'),
    ('Participación infantil', 'Fomento de la participación de los niños en decisiones educativas.'),
    ('Proyecto de vida / Expectativas a futuro / Orientación vocacional', 'Apoyo en la planificación del futuro académico y profesional de los estudiantes.'),
    ('Sexualidad', 'Educación sobre temas de sexualidad y desarrollo personal.'),
    ('Arte', 'Fomento de la creatividad y expresión artística en niñas y niños.'),
    ('Computación', 'Enseñanza de habilidades digitales y uso de herramientas tecnológicas.'),
    ('Educación física', 'Promoción del ejercicio y actividades deportivas para el bienestar infantil.'),
    ('Música', 'Desarrollo del sentido musical y expresión artística a través del sonido.'),
    ('Visitas fuera de la escuela', 'Experiencias educativas en empresas o lugares recreativos.'),
    ('Maestro para clases de arte', 'Docente especializado en enseñanza artística para estudiantes.'),
    ('Maestro para clases de educación física', 'Docente enfocado en el desarrollo de habilidades deportivas y motrices.'),
    ('Maestro para clases de idiomas', 'Docente que facilita el aprendizaje de idiomas adicionales.'),
    ('Persona para apoyo administrativo', 'Personal encargado de tareas administrativas dentro de la institución educativa.'),
    ('Persona para apoyo en limpieza', 'Encargado de la higiene y mantenimiento del espacio escolar.'),
    ('Psicólogo', 'Especialista en salud mental y bienestar emocional para la comunidad escolar.'),
    ('Psicopedagogo o especialista en BAP', 'Profesional que apoya a estudiantes con barreras para el aprendizaje y la participación.'),
    ('Suplentes de docentes frente a grupo', 'Educadores que cubren ausencias temporales de docentes titulares.'),
    ('Terapeuta de lenguaje o comunicación', 'Especialista en desarrollo del lenguaje y habilidades comunicativas.'),
    ('Adecuaciones para personas con discapacidad', 'Construcción de rampas y otras adaptaciones para accesibilidad.'),
    ('Agua', 'Solución de fallas de agua, instalación de filtros, bombas, tinacos o bebederos nuevos.'),
    ('Árboles', 'Plantación de nuevos árboles, poda y arreglo de jardineras.'),
    ('Baños', 'Reparación y remodelación de sanitarios, plomería y lavamanos.'),
    ('Cocina', 'Construcción o remodelación de la cocina escolar.'),
    ('Conectividad', 'Instalación de routers y mejora en el acceso a internet.'),
    ('Domos y patios', 'Estructuras para domo, malla sombra y nivelación de patios.'),
    ('Luz', 'Solución de fallas eléctricas, conexión de luz, instalación de focos y paneles solares.'),
    ('Muros, techos o pisos', 'Reconstrucción de muros cuarteados, impermeabilización y remodelación de pisos.'),
    ('Pintura', 'Mantenimiento y mejora de pintura en instalaciones escolares.'),
    ('Seguridad', 'Construcción o reparación de bardas perimetrales, cámaras de seguridad y cercado.'),
    ('Ventanas y puertas', 'Instalación de nuevas ventanas, puertas y protecciones.'),
    ('Didácticos', 'Materiales educativos como plastilina, cartulinas, hojas, marcadores, crayolas, lápices, colores, juegos didácticos, microscopios, etc.'),
    ('De educación física', 'Sogas, pelotas, aros, tinas, balones, porterías, redes para voleibol y canastas de baloncesto.'),
    ('Tecnológico', 'Computadoras, impresoras, proyectores, pantallas, bocinas, extensiones, cables HDMI y otros dispositivos digitales.'),
    ('Literarios', 'Libros infantiles, manuales, libros de texto, libros en braille, libros macrotipo, material para estudiantes de lengua indígena y programas de estudio.'),
    ('Mesas para niños/ mesabancos', 'Mobiliario adecuado para el trabajo escolar de los estudiantes.'),
    ('Mesas para docentes', 'Espacios de trabajo adecuados para los maestros.'),
    ('Comedores', 'Mobiliario para áreas de alimentación en la escuela.'),
    ('Sillas (para niños o para maestros)', 'Asientos adecuados para estudiantes y docentes.'),
    ('Estantes, libreros o cajoneras', 'Almacenamiento para materiales educativos y libros.'),
    ('Pizarrones', 'Superficies de escritura para clases y actividades escolares.'),
    ('Desayunos', 'Suministro de desayunos nutritivos para la comunidad escolar.'),
    ('Fórmula', 'Provisión de fórmula infantil para niños que lo requieran.'),
    ('Transporte', 'Nuevas rutas de camiones, transporte escolar, entrega de bicicletas, etc.'),
    ('Arreglo de camino', 'Construcción y mantenimiento de caminos, puentes en arroyos, aplanadora de camino, luminaria, etc.'),
    ('Apoyo en gestión de escrituras', 'Asesoría legal para la regularización de inmuebles sin escrituras.');